### ISSUE TITLE
Crafting difficulty calculation

### ISSUE THREAD

**Issue by nlblunt** [AngryBeaver/bsa-fallout#1]
In Fallout 2d20, the difficulty of the crafting check is the item complexity- the associated skill, minimum of 0. There is currently a Tests - Hits input for the complexity(difficulty) of the item. However, the module does not reduce this difficulty by the skill.

IE: Item to Craft complexity= 3, initial difficulty = 3
Skill = Repair, Repair skill = 2
Final difficulty = 3 (initial) - 2 (skill) = 1.

The player would need to roll 1 success in order to craft this item.

If the final difficulty = 0, a roll is still made to see if there are any 'complications'.

**Comment by AngryBeaver** [comment]
So if i understand you correctly the outcome of the recipe e.g. the items you craft descide the complexity of the check.
The problem is my recipes would allow for multiple items as result. So i can not create a check that would just read the "result" complexity.
As far as i know i implemented it in a way that you can set the difficulty on the recipe while this is as you said usually the complexity of the item it would allow also to set a complexity if you write recipes with multiple items as result.
So this part i would left untouched.

The next is my check is not reduced by the skill level.
Well as i have no idea how this system is working i just add something with skills.  I will have a look if i can implement it in the way you mentioned.

**Comment by AngryBeaver** [comment]
The hits fields is usually for how often do you want this check to be made so that you finally get your crafted items. 
So while you could use it to achieve something similar to what you wanted it should not be used for it as it would allow you to do muliple rolls if you did not have enough succeeds at the first roll. 


So here are the changes for 2.0.1 :

I added a complexity input for every skill check you can set this now.
When you roll your skill the amount of required success is maximum(0,(complexity-skill)) so at least 0.
For the propose of the crafting process i ignore complications. ( i kinda interpreted it into what you have written above )
(before success had been reduced by the amount of complications you roll).


So with this you should change the hits back to 1 again so you only will need to make one skillcheck. And then add the complexity value to your recipes.
